version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
nuget:
  account_feed: true
  disable_publish_on_pr: true 
install:
- ps: >-
    nuget restore

    $env:SHARPYAML_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:SHARPYAML_VERSION_SUFFIX = ""
           $env:appveyor_nuget_push = 'true'
        }
      }
    }
build:
  project: SharpYaml.sln
  verbosity: minimal
before_package:
- cmd: msbuild /t:pack /p:Configuration=Release SharpYaml/SharpYaml.csproj
artifacts:
- path: SharpYaml\Bin\Release\*.nupkg
  name: SharpYaml Nugets
